locations: 
  # CA
  - geo: [ -120.79, 37.193 ]
    categories: 
      - type: 1               # successfull
        count: 42
      - type: 2               # in progress
        count: 13
      - type: 3               # failed
        count: 7  

  # LA 
  - geo: [ -118.79, 34.193 ]
    categories: 
      - type: 1               # successfull
        count: 80
      - type: 2               # in progress
        count: 47
      - type: 3
        count: 116            # failed

  # NY
  - geo: [ -74.79, 40.193 ]
    categories: 
      - type: 1               # succesfull
        count: 219
      - type: 2               # in progress
        count: 40
      - type: 3               # failed
        count: 28

properties:
  fields: 
    5065: 
      lookup: 
        1: Pedestrian
    5074: 
      lookup: 
        1: Successfull
        2: In progress
        3: Failed
      name: Deployments
  attribution: Deployments
  description: Deployments information
